spring.application.name=employee-h2database

spring.datasource.url = jdbc:h2:mem:demo;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect



file.upload.image_path =C:/Users/Belen ITS/Documents/uploads/images

file.upload.resume_path = C:/Users/Belen ITS/Documents/uploads/resume


logging.level.root=INFO

logging.level.com.example.employee=DEBUG

